[package]
name = "nat64"
version = "0.1.0"
authors = ["Rayhaan Jaufeerally <rayhaan+github@rayhaan.ch>"]

[dependencies]
"libc" = "0.2.41"
"pnet_packet" = "0.21.0"
"ipnetwork" = "0.13.0"

[dependencies.pnet]
version = "0.21.0"

[build-dependencies]
bindgen = "0.37.0"
